# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.IntegerField(default=1),
        ),
    ]
