# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dash', '0002_auto_20171115_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='from_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='posts_from_user', to='user_dash.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_user', to='user_dash.User'),
        ),
    ]
