# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 04:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_dash', '0003_auto_20171116_0047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='from_user',
        ),
    ]
